from dotenv import load_dotenv

import os

load_dotenv()

class Settings():

    # Common Variables
    NEO4J_DATABASE=os.getenv("NEO4J_DATABASE")
    NEO4J_URL=os.getenv("NEO4J_URI")
    NEO4J_USERNAME=os.getenv("NEO4J_USERNAME")
    NEO4J_PASSWORD=os.getenv("NEO4J_PASSWORD")

    LITELLM_DEPLOYMENT_NAME=os.getenv("LITELLM__DEPLOYMENT_NAME")
    LITELLM_API_KEY=os.getenv('LITELLM_API_KEY')
    LITELLM_API_BASE=os.getenv('LITELLM_API_BASE')

    LITELLM_EMBEDDING_DEPLOYMENT_NAME=os.getenv("LITELLM_EMBEDDING_DEPLOYMENT_NAME")
    
    # LangFuse
    LANGFUSE_PUBLIC_KEY=os.getenv("LANGFUSE_PUBLIC_KEY")
    LANGFUSE_SECRET_KEY=os.getenv("LANGFUSE_SECRET_KEY")
    LANGFUSE_HOST=os.getenv("LANGFUSE_HOST")


    MONGODB_DATABASE=os.getenv("MONGODB_DATABASE")
    MONGODB_URI=os.getenv("MONGODB_URI")

    MONGODB_COLLECTION_CONFIG=os.getenv("MONGODB_DATABASE")
    MONGODB_COLLECTION_KG_METADATA=os.getenv("MONGODB_DATABASE")
    MONGODB_COLLECTION_PDFS=os.getenv("MONGODB_DATABASE")
    MONGODB_COLLECTION_PDFS_METADATA=os.getenv("MONGODB_DATABASE")

    CHUNK_OVERLAP=int(os.getenv("CHUNK_OVERLAP"))
    CHUNK_SIZE=int(os.getenv("CHUNK_SIZE"))


# Initialize settings
settings = Settings()